site_name: Reading

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - 4 hour Week Chef (Tim Ferris): '4_hour_week_chef.md'
  - A Liberated Mind (Steven C. Hayes): 'a_liberated_mind.md'
  - Focus (Leo Baubauta): 'focus.md'
