site_name: Reading

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - 4 hour Week Chef (Tim Ferris): '4_hour_week_chef.md'
  - A Liberated Mind (Steven C. Hayes): 'a_liberated_mind.md'
  - Focus (Leo Baubauta): 'focus.md'
  - The Little Book of Common Sense Investing (Little Books. Big Profits) (Bogle, John C.): 'the_little_book_of_common_sense_investing.md'
